var rule = {
 title: '爱情影院',
  host: 'https://loveqtv.com',
  url: '/index.php/vod/show/id/fyclass/page/fypage.html',
  searchUrl: '/index.php/vod/search.html?wd=**&submit=',
  searchable: 1,
  quickSearch: 1,
  filterable: 1,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  class_parse: '.head_menu_a li:gt(0):lt(6);a&&Text;a&&href;.*/(.*?).html',
  play_parse: true,
  cate_exclude:'资讯|其他',
  lazy: '',
  limit: 6,
  推荐: '.cbox_list;ul&&li;a&&title;a&&data-original;.vodlist_top&&Text;a&&href',
  double: true,
  一级: '.vodlist&&li;.vodlist_thumb&&title;.vodlist_thumb&&data-original;.pic_text&&Text;a&&href',
  二级: {
    title: 'h2&&Text',
    img: '.vodlist_thumb&&data-original',
    desc: '.data_style&&Text',
    content: '.content_desc&&span:eq(0)&&Text',
    tabs: '.play_source_tab&&a',
    lists: '.playlist_notfull:eq(#id) a',
  },
  搜索: '.vodlist&&li;.vodlist_title&&title;.vodlist_thumb&&data-original;.pic_text&&Text',
}